<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form
    ref="vForm"
    :model="formData"
    :rules="rules"
    label-position="left"
    label-width="150px"
    size="small"
    @submit.native.prevent
  >
    <div class="static-content-item">
      <div>分组表单</div>
    </div>
    <div v-show="false" class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="never">
        <div slot="header" class="clear-fix">
          <span>发件信息</span>
          <i class="float-right el-icon-arrow-down" />
        </div>
        <el-row>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="发件人姓名" prop="发件人姓名" class="required label-center-align">
              <el-input v-model="formData.发件人姓名" type="text" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="发件人号码" prop="发件人号码" class="required label-center-align">
              <el-input v-model="formData.发件人号码" type="text" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="是否保密" prop="是否保密" class="label-center-align">
              <el-switch v-model="formData.是否保密" />
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="发件人地址" prop="发件人地址" class="required label-center-align">
              <el-input v-model="formData.发件人地址" type="textarea" rows="3" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-card>
    </div>
    <div v-show="false" class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="never">
        <div slot="header" class="clear-fix">
          <span>收件信息</span>
          <i class="float-right el-icon-arrow-down" />
        </div>
        <el-row>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="收件人姓名" prop="收件人姓名" class="required label-center-align">
              <el-input v-model="formData.收件人姓名" type="text" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="收件人号码" prop="收件人号码" class="required label-center-align">
              <el-input v-model="formData.收件人号码" type="text" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="接收时间段" prop="接收时间段" class="required label-center-align">
              <el-checkbox-group v-model="formData.接收时间段">
                <el-checkbox
                  v-for="(item, index) in 接收时间段Options"
                  :key="index"
                  :label="item.value"
                  :disabled="item.disabled"
                  style="{display: inline}"
                >{{ item.label }}</el-checkbox>
              </el-checkbox-group>
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="收件人地址" prop="收件人地址" class="required label-center-align">
              <el-input v-model="formData.收件人地址" type="text" clearable />
            </el-form-item>
          </el-col>
        </el-row>
      </el-card>
    </div>
    <div v-show="false" class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="never">
        <div slot="header" class="clear-fix">
          <span>补充信息</span>
          <i class="float-right el-icon-arrow-down" />
        </div>
        <el-row>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="送货时间" prop="送货时间" class="required label-center-align">
              <el-input
                v-model="formData.送货时间"
                is-range
                class="full-width-input"
                format="HH:mm:ss"
                value-format="HH:mm:ss"
                clearable
              />
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="价格保护" prop="价格保护" class="label-center-align">
              <el-slider v-model="formData.价格保护" :step="10" />
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="其他信息" prop="其他信息" class="label-center-align">
              <el-input v-model="formData.其他信息" type="textarea" rows="3" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-card>
    </div>
  </el-form>

</template>

<script>
export default {
  components: {},
  props: {},
  data() {
    return {
      formData: {
        发件人姓名: '',
        发件人号码: '',
        是否保密: true,
        发件人地址: '',
        收件人姓名: '',
        收件人号码: '',
        接收时间段: [],
        收件人地址: '',
        送货时间: null,
        价格保护: null,
        其他信息: ''
      },
      rules: {
        发件人姓名: [{
          required: true,
          message: '字段值不可为空'
        }],
        发件人号码: [{
          required: true,
          message: '字段值不可为空'
        }],
        发件人地址: [{
          required: true,
          message: '字段值不可为空'
        }],
        收件人姓名: [{
          required: true,
          message: '字段值不可为空'
        }],
        收件人号码: [{
          required: true,
          message: '字段值不可为空'
        }],
        接收时间段: [{
          required: true,
          message: '字段值不可为空'
        }],
        收件人地址: [{
          required: true,
          message: '字段值不可为空'
        }],
        送货时间: [{
          required: true,
          message: '字段值不可为空'
        }]
      },
      接收时间段Options: [{
        'label': '上午9:00 - 11:30',
        'value': 1
      }, {
        'label': '下午12:30 - 18:00',
        'value': 2
      }, {
        'label': '晚上18:00 - 21:00',
        'value': 3
      }]
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {},
  methods: {
    submitForm() {
      this.$refs['vForm'].validate(valid => {
        if (!valid) return
        // TODO: 提交表单
      })
    },
    resetForm() {
      this.$refs['vForm'].resetFields()
    }
  }
}

</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }

  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }

    .el-rate {
      margin-top: 8px;
    }
  }

  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }

    .el-rate {
      margin-top: 6px;
    }
  }

  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }

    .el-rate {
      margin-top: 4px;
    }
  }

  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }

  .clear-fix:after {
    clear: both;
  }

  .float-right {
    float: right;
  }

</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }

  div.tab-container {}

  .label-left-align ::v-deep .el-form-item__label {
    text-align: left;
  }

  .label-center-align ::v-deep .el-form-item__label {
    text-align: center;
  }

  .label-right-align ::v-deep .el-form-item__label {
    text-align: right;
  }

  .custom-label {}

  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
      margin: 0;
    }
  }

</style>
